<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_eye__password bx bx-show</name>
   <tag></tag>
   <elementGuidId>615465db-67ba-409e-9a95-8df0c1cd04d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.eye__password.bx.bx-show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='togglePassword']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5f787075-eb38-4c6f-9c1a-dbfab5344e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eye__password bx bx-show</value>
      <webElementGuid>62cf53ed-cbfb-479a-b110-840e66c83365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;togglePassword&quot;)/i[@class=&quot;eye__password bx bx-show&quot;]</value>
      <webElementGuid>c8b14f27-5558-428f-a24e-007b10651166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='togglePassword']/i</value>
      <webElementGuid>8a2937a5-b328-43ef-b893-1a27daecd5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>7c756096-b3c8-44ac-9071-e4fcb55532b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
