<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_stairs_rc-image-tile-33_1_2</name>
   <tag></tag>
   <elementGuidId>ce12953a-7f65-4f65-84a5-452bcb8e82b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.rc-imageselect-tile >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>909eeede-93e1-4037-8022-ec950d701603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>5111c2cb-e5ea-48b7-9d59-2314551daea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>d5c992ee-8027-428b-8df1-d7cf05a3a0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>a455fa46-a67f-41f4-9e94-ff9f4e0c0b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>f619ffbf-71de-4414-accb-060b628d2d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>f18aa1b9-c879-47c3-97bc-41e26f51f3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')]</value>
      <webElementGuid>4a4efa31-5f71-42bf-8e61-74128506cc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>139904c2-00e3-42a0-adad-ea1f2800d31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>c170e26f-2def-4fb6-bf9d-b6559245fd1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
