<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>64d5bb3c-3835-4f47-af2a-70343e7536f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a8894ce-ced7-4610-be92-81f380ed207f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>12f95122-32b8-484e-b14a-c8b106e7be11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8</value>
      <webElementGuid>532d41d5-ba18-4991-a1ef-5b9e2309345b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>6251eb60-00c0-4f6b-b87d-d6d74c40545a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>fbd9f481-6845-415d-910a-19b565821ee5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>6c8be981-428b-4daf-9234-8cb7dcb08838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8')])[7]</value>
      <webElementGuid>599c3108-6e12-4166-bcd1-5177e5819c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>5061f7b5-5625-4dca-ac61-81c2fef7e823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8']</value>
      <webElementGuid>ad8d4f9d-1841-4ed7-83b2-fa11c316aaab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
