<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28</name>
   <tag></tag>
   <elementGuidId>f7f8a2d2-b419-4ea2-ac73-849c56f97841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(2) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>17cf4106-ae14-4cf5-878f-65afdd1dcc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>a9cc64e2-3dfd-4d81-9d25-50096e750647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6</value>
      <webElementGuid>e51ad93c-2ccc-4a68-b69a-4de6fc8009e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>3d7e6b55-f714-4857-ae2a-6664b46314ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>6692b022-c600-4b0f-a97e-baf0958efb8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      <webElementGuid>b3a53772-0319-4a0b-9f24-5da6c09e2e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6')])[2]</value>
      <webElementGuid>dd9fd63a-9f7f-446c-b096-f3023d8bf5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>82e007c9-f137-41c8-9ede-624d37652b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6']</value>
      <webElementGuid>b9e0f40d-b6a9-4f3f-91a6-31a2a987cc08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
