<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>356e1618-9cbc-4a6d-8682-5cc8170ff6ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6765919f-3056-4a0c-9f43-614f8823aa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>3ec6208d-aeb4-42b0-8b31-2365ae049c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=2</value>
      <webElementGuid>b0bcc97e-0037-4a5f-9c57-81110df30d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>50d9111e-fa98-4848-a377-3005477b5dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>18b03a5b-916a-45da-abf1-65c837deee16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      <webElementGuid>ccac3b33-dd52-422b-b4a2-8cb74a439f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=2')])[5]</value>
      <webElementGuid>26670efa-0f33-450a-9a00-e6fe522394ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
      <webElementGuid>c54046f0-77ea-4b1c-9076-dd8514f150ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=2']</value>
      <webElementGuid>35bcc4e4-5efd-4890-913b-71fe1d135193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
