<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20</name>
   <tag></tag>
   <elementGuidId>3dbaaba1-0909-4a7e-a55b-98a4699c1c65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e56c094b-2f5a-43c6-a016-4953f1fe11f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>bdb01e66-b606-43cf-bacb-0499225989f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6</value>
      <webElementGuid>5fc83d47-a25f-4f15-87d1-660df3c8b018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>c422183a-0c76-4abd-ae04-a8b47eaacf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>9fd9d6ee-09fd-4992-ae8a-7aff4c65b82f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[3]/div/div/img</value>
      <webElementGuid>12a8dfa8-140b-4365-92b0-ca5b220271ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6')])[15]</value>
      <webElementGuid>657f1874-6e29-4986-a2e3-fb294a478e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/div/div/img</value>
      <webElementGuid>63adf908-053f-4270-a55e-82a1c0f49d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6']</value>
      <webElementGuid>3f55e480-6abb-42ba-9d8d-6a50b0da63db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
