<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_stairs_rc-image-tile-33_1</name>
   <tag></tag>
   <elementGuidId>84b3c3f3-6a94-47d6-9067-844f22a383b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e18de22f-44e2-497c-b53f-111f1577243d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>1f1538be-71c1-4e3c-86bb-f68f6c120c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>84e1ee6c-3643-4093-93ce-f8f5e78aa6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>ffc33a3c-0441-4589-b313-caf5ecdd8340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>015d34bc-dd9a-410b-973e-e394790bee04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>133a6576-5766-499e-b89a-938bf4f958cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')])[9]</value>
      <webElementGuid>073cc543-f672-4506-93cd-419b54a40b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>16e21ed0-f80d-46d3-91ec-3317ac4fb413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>d68d69fc-4c95-48df-b0c0-f00a878d44a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
