<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>21dfb8e3-61a6-48f3-bd43-6e8c4875e9ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5f74b495-30ea-43d8-85a9-e6711be0b699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>19a74151-c282-449f-8257-7fbf4d3b6c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=2</value>
      <webElementGuid>0a71ffdb-8343-4097-a18a-6bc6d5968c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>41971afa-bf1c-4b7e-b67b-7be779213c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>40461ec5-dc95-4436-af35-c839d026c93f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      <webElementGuid>98095485-1497-40a2-92d8-a96b5b732072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=2')])[9]</value>
      <webElementGuid>bde2965a-0a16-4c9e-b67b-48ef536e9c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
      <webElementGuid>27feac39-7acb-45aa-96e0-f7bb2b0ef0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=2']</value>
      <webElementGuid>40380afa-f28e-4427-ada6-3a0a104a5c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
