<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_33_34</name>
   <tag></tag>
   <elementGuidId>982bef1d-1318-4089-9e88-4983b50bb04b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>70438d8b-1e09-4919-829d-a485de2b0d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>c892bbf6-aca4-45a7-b7c5-133618417ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a</value>
      <webElementGuid>12444115-7603-49e5-9d2c-dffa1c3e8bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>e5f32a61-9b8c-495b-9f0f-e0b4ebe11eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>c11ac0a6-11ad-411f-b687-5ec6b6a034f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>fdbeeca0-9ff2-42a1-a7d7-7c7f1a296f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a')])[6]</value>
      <webElementGuid>d514edef-fdfd-46aa-a7e2-6eedb98fe78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>2c868635-cbda-4dd7-b120-aaf59e1c9066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a']</value>
      <webElementGuid>5cd2641b-b3f2-4403-b6ff-ac089fa14481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
