<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15</name>
   <tag></tag>
   <elementGuidId>6258c9c5-a359-4030-950b-5c8bcebaf0a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>99232775-b142-4329-95ce-3553b61c6e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>51cee7a4-c876-4268-b0a9-9fe05821f44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8</value>
      <webElementGuid>a35f2af0-5a61-4c91-a9d4-303b1c5f48e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>c0b693f4-1f4b-406c-8243-799f278e34aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>58e3e539-5b03-4ede-af90-abbf00e8f52c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>ceedec42-0fdd-455b-a0c0-1c278c5378e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8')])[11]</value>
      <webElementGuid>82bf2b44-52b4-4f2b-807f-6c09dc363bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>ffb80895-d786-4eaf-8419-a61781a22e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8']</value>
      <webElementGuid>4d89e12d-c657-4633-826e-eade0fa433dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
