<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21</name>
   <tag></tag>
   <elementGuidId>6c068e30-5def-47ff-bdc2-47e5bd74f16d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>58d9e330-ea6a-4cee-b9e1-9f46e22cd43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>074c9a3f-3edf-46bf-b335-4533f2f54237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6</value>
      <webElementGuid>cab0c99a-6956-40c3-8875-787239d01c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>e2202fd5-e326-487b-8de1-48643edc8765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>cdeb4f94-317f-4459-9350-f9dc197cf3fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      <webElementGuid>2fc586f5-c760-44b9-a4af-8d2ca3fccbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6')])[13]</value>
      <webElementGuid>f18a546e-7308-48ce-9cc5-96d3c95473f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/div/img</value>
      <webElementGuid>3815d696-1471-42c8-9897-95b2503df711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6']</value>
      <webElementGuid>8bb6a3cb-7fa8-427c-9a31-df96df94d441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
