<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_33</name>
   <tag></tag>
   <elementGuidId>3c2a5578-cd62-4872-b8b2-34a4d184ddd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>78eff3c8-9d88-4395-8fa4-53155ab1e397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>546694d1-152b-41e8-af7a-98ed34cb8bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a</value>
      <webElementGuid>e3bcc603-c9ba-4200-a1b6-06a625826e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>ba777b65-5121-4eff-b373-9356ba38bf8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>28187da9-a0d8-4bcf-abe4-17896c32c3da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>a44278ef-2898-4ac0-a173-760644e9ba92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a')])[10]</value>
      <webElementGuid>e7b34e28-0f72-40d7-afdd-95c6b92d6907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>e73e842f-e712-4aea-af88-24d5337bcccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a']</value>
      <webElementGuid>ce67377f-d5e8-4cf8-b022-a57ecb72bade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
