<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_stairs_rc-image-tile-33_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>4f657aeb-09b3-4c4f-8197-c66422fc3016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(3) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>785a5504-ddcb-4a26-b2cc-0fab6da2a826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>b4eff0c7-812c-499e-bee6-6efdca8b36f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>d4163f53-e395-4318-9f3f-4686de8439e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>83843530-8839-497a-b36e-1c871435fcd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>6d22fc50-21f2-4633-8378-5ba808fd5a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      <webElementGuid>d601019d-770e-4b0b-940e-22b48aa36a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')])[3]</value>
      <webElementGuid>7a5e0494-3047-459b-868d-b6bb4bf4587f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
      <webElementGuid>0df4f739-595c-45ca-a15a-e8b6743a5f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>9d7a7074-dff6-45f5-8131-60e203d910a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
