<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>885d47cf-db10-40ec-84cb-10826d55847e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b2c605fa-3bad-44b5-b8fb-8b33052f044f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>9eb57d6c-1d21-4c59-987f-84c4120002fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=2</value>
      <webElementGuid>c93c7b1c-edf5-4b63-870f-87fc7052b794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>a20c9b05-1956-4f66-b981-42ea3b4f54cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>6bde6439-d205-4102-bbe9-389d8defecc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>6a82b913-2a8c-4c55-8c74-d7d9fc57bd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=2')])[10]</value>
      <webElementGuid>a138f7c2-7068-45a3-8b66-8c4d79ba2e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>64c44e3a-b19d-4c39-a378-f8e445e8acb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=2']</value>
      <webElementGuid>556760fd-0e0e-49d6-a22f-8d73ac014c11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
