<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>9fcef882-0f69-4081-b04b-026db2b3317b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(4)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d1fe2693-2a72-454c-889e-22c58d0756e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>39556367-39db-4253-a0bc-adf773f12abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>d7259245-5cc1-4bef-876f-ab942db0bfd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>c3de67df-80fc-4c6e-882d-5828323d9314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>b951699b-6768-4795-902c-cec822781b4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      <webElementGuid>9ff86918-2dcd-4740-a569-c201d6f04c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')])[12]</value>
      <webElementGuid>0557b578-b810-40d8-b410-23e9974ac23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/div/img</value>
      <webElementGuid>5ce581b8-36c5-4358-a691-dbc4938c4606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>c2d164b8-1846-4124-a6ea-ccafa3d028ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
