<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31</name>
   <tag></tag>
   <elementGuidId>a8ddf280-16cb-44a3-bc3b-e4a199dcc6f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(4)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8e812ebf-34c6-4a9c-9769-15e6db4bcaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>111ae270-fe34-48ca-aee2-3809aec714c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a</value>
      <webElementGuid>4bbf5d9b-0aaa-4591-9eec-0428ef3140f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>0ee12622-4f06-45ac-89e3-2470a5852663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>e97b03fb-bdf0-45f1-bafd-8e86f941d8d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      <webElementGuid>5a6e58fd-4c24-4de6-a81c-dc668887452a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a')])[12]</value>
      <webElementGuid>288f9b6d-32c9-4177-a77b-9f158146e920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/div/img</value>
      <webElementGuid>282663b3-4c53-467f-a935-090ef85ed29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a']</value>
      <webElementGuid>b6b79085-909e-48ba-91a0-d6d830266395</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
