<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>f1751fe2-1f7a-4e1e-b570-1d7f595f4550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e3e1d522-f9ce-4942-a691-40b28cba32f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>144c2b8b-17c7-41b2-8518-0653bec93984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>762d0135-893e-44b4-b932-43ba9269d778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>e8161985-8d80-426f-88a7-23561935d014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>f61af0a9-fc0a-4198-af2b-350eab242c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>6d9172cb-0ca2-4d0d-903c-abf45f576c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')])[11]</value>
      <webElementGuid>b456501c-234c-4af5-b091-38052d4379a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>9f2d193e-f7e0-4f88-9cca-c128c561a288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6MN3qd53XxP4PHVzAFGFTt8tWc8SbUxY_oIkSDVJyTOHoyVOro0T-O17NW4zV5RsF02kQ3Cg8QjrPvr7HMqpy21sqY-R6dN5TMfeg-F-tZM9o-myEu_vdTXYi6z5Ephru7IROJNCWBUqkoJDr2OcsZRcQEDixj-3NPLc_p6A9779x8i4RAt05gGJDXh6UHyHddwroWp5uI-02YjDbpPyym80fziEESL8EjYB_-kwaDLhsWpIw&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>8c6a8a63-1fb5-4891-a00c-877890b95bfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
