<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>9f403011-816c-4420-bdc9-2460a856c4c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>70ce3820-906d-46cb-8fca-7653abbac943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>217ab7c1-b937-4ae0-a0e9-037fbc526e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8</value>
      <webElementGuid>027c6f85-2dea-4808-9c52-7aa13067cdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>76cc7daa-2713-429b-a0df-96d5947579f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>47adefbd-92be-4d86-b902-1c16d1cf6631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>320c1c93-d684-44d1-92e7-ba2729b3ea57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8')])[6]</value>
      <webElementGuid>13df675a-2d79-468c-8de4-65187be8acc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>5a2c7862-3e1e-49a0-91a1-ebfbb1a3345b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8']</value>
      <webElementGuid>fca80f9b-c344-40d2-9aa9-9e66cd6d90c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
