<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_stairs_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>53adcd94-bfd4-4ae9-ae91-f88f3e8a9ab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>28a249bd-84df-426d-b442-16f092f81a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>c4cf8ce6-4175-4809-8380-2928f1458d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>7ab7897d-3366-4716-8477-b90e4f06c78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>1659a139-053a-4acb-a815-8139279582e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>f9d8f311-5e88-4c3e-ad63-02edc87d0a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>ba0a5816-46cd-4cae-9d8c-31b36895a25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')])[8]</value>
      <webElementGuid>3d762fdc-d9bf-47f2-a3a4-5475c4e9c636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>b8d0abbe-6eb3-40dc-b063-e40a76bdeaa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>33822006-7227-4326-b770-2672099d9d03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
