<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22</name>
   <tag></tag>
   <elementGuidId>32a27281-a3ae-499d-93ef-8a8af0dacb51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a99c02b0-27d4-4f4b-b7a2-2ebf8380ccbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>ea1a5064-7ecd-41aa-b58b-d2de833944ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6</value>
      <webElementGuid>f268fa91-6b53-459f-a85e-9a4b7b227cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>c4333d66-b92a-42e9-8fc3-0c5dfb67b53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>7909d6d5-7ba8-47a4-820a-bbaa3060651e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      <webElementGuid>c923928f-d59c-455c-a351-a719c3aa169f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6')])[9]</value>
      <webElementGuid>3b7f3f6e-0cbc-4282-8235-57bc3e1070d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
      <webElementGuid>db99eb35-ca34-432d-ab35-588e7ecc6b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6']</value>
      <webElementGuid>3cf2f93c-0b3e-4982-918e-69c5d0fe948e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
