<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_stairs_rc-image-tile-33_1_2_3</name>
   <tag></tag>
   <elementGuidId>550c3a3a-be93-4947-b8fc-1c80ffe63e54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>50a5905f-b880-4bad-8b92-55263d2901fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>e6b9f2df-8a6a-4ad6-a4fc-a310682249b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>4e30d2ec-1005-4a2a-aa99-a931fab6020c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>d970376e-b50e-4d4e-a063-678e8e2e444a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>285ad91b-e198-4929-a13d-2566e416c7fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      <webElementGuid>5cf582e5-74c3-461a-a25b-ceb7d1c2b236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')])[4]</value>
      <webElementGuid>63b7cdf2-9037-46c0-bcbf-ebf52075d838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
      <webElementGuid>79014fab-ece5-4575-b9ef-55f1e861cb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7Ue5-UyEfTGgL9SQufuv75pSjY2KPAWIIUNSSxzlI-ApqbGQKCuu_C8rrAdlpLaJTe336LHMYz85NUHndMb468rQsyDl9L5JDFee_qa-VOGdZAzuw2q-fPYGNGwOrLsV5k3ScKXsvynFQE7MY5uDofrXcdl54opT75b5wa3Opt4QBx7F27pGV-SQoTfCuR9ExtpdC6u4suoQGPCMV82KKmeF6WQ7976pTn8gMs45kDuVlzY74&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>5b189588-ff4f-4770-915a-2c058f585b47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
