<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24</name>
   <tag></tag>
   <elementGuidId>558b477f-ad39-451a-934e-4558ae7210da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>10a4e2fd-467a-43df-8705-34f6e7b86f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>31139a82-24ae-400c-ab17-c7730bd05e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6</value>
      <webElementGuid>20e82aa9-1968-4e6f-b614-025c09688132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>ee5f9147-0926-48a8-8003-1dcf1d150e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>7e3ca7f8-9120-464c-9f77-123594da9b29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>8bc5fe07-3eda-490c-8343-b465dc97e4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6')])[11]</value>
      <webElementGuid>a9af9f8a-31d5-4497-a062-be1cb1e21964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>6731a969-8b8a-46fb-8957-e82ec9309f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lyNgAlaogPDlWvefW3N8bh2mnR9v8jU8cjENuLHYla7lXKE6YXZMQ9mQscCLrkLQ8yNO34h4mdRmu_iwPKIxvyMnyxdm8TYZIrXui6n-jKdAAeQ0OXR49388PbnKzqK80QGjqMedYWpsDCorVK6PLCUmSrdmt16F6P1PN71wsVAM4o6LlRfntVxxSWbZnH9NfA-egrca3WxgwfUrQ61bPEAvEDYlwj4v9Ifs3p_iG-Xz2Mek&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=5985d8891edae6f6']</value>
      <webElementGuid>c8acc925-9f80-4c04-bf53-e3d76f6222a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
