<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13</name>
   <tag></tag>
   <elementGuidId>2002d859-1e5e-4161-8ce9-ea5a2d2bb163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(3) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0e654afe-b210-4ee7-b382-91d553113c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>d7137651-a05f-4593-bcd5-0c808a35e8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8</value>
      <webElementGuid>38be63d6-3ff5-4f5d-addc-d136cc181463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>bac43180-136d-4e7d-aad5-02fff141aac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>12da126a-fcdc-4281-a644-2da336b3f3ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      <webElementGuid>840b68e1-dcfe-42ca-a695-8cbe1062cfbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8')])[3]</value>
      <webElementGuid>2cfee824-fddf-4ddd-8cca-0b5930b2ce38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
      <webElementGuid>7775570b-a279-41b8-8ff7-6e46836878de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8']</value>
      <webElementGuid>dd5243dc-c595-4f63-88f5-755157053743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
