<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32</name>
   <tag></tag>
   <elementGuidId>5d9db7e7-ae73-437b-bcf9-87ed8e6d8f95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b200d830-9c7c-4da1-8a5b-04cc153a8e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>1ef3f6c4-272b-42d9-a131-41594bd64430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a</value>
      <webElementGuid>b9d4bed1-b361-4084-9995-eaedb48cdf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>304232bd-0071-4850-845c-6f917159312f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>bedee8e7-6d9e-4db3-a083-ad67c5553fd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>29caa258-a0a9-49cf-b805-57e77cbb6068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a')])[11]</value>
      <webElementGuid>b2e8454b-2e59-48fd-91f4-84afcb0e9f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>0961917a-013c-4127-89b9-9502e514709c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a']</value>
      <webElementGuid>46cead5b-2fbe-4347-9988-0bfe5db46be9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
