<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_33_34_35</name>
   <tag></tag>
   <elementGuidId>4aacd352-1a90-4880-bce5-9d55af24579b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>79327208-5232-4400-8b17-79f6c1239328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>78e309b8-ef73-4f5b-b4a3-9987229d9649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a</value>
      <webElementGuid>d4d7f641-95fa-4ca0-b1ff-ebfceee5b1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>b98a0ff6-5567-4e96-9063-07b15f5d5d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>43f4aa08-6046-480d-8859-6e5c72819de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>6d8eb564-dbf0-4416-b586-c21498ff5559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a')])[7]</value>
      <webElementGuid>ff86af4c-3cd3-4f53-9f23-4ba69ab53812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>f040d1c3-4844-4f23-baf2-f2077b9e8f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4PHXkfs3-ciZYF-VF9j1tkofPUAtBBlQ84kJxwP-oWxrZGzSoQwDm8GLbAw-KBtI0UIcEUKm8XenKKjbgysyiy30CwVilUpLQ6M5YdnaWQ_4wVd0xjk4tGK6SV1lz8qmK1oVOx1KGtCcyNGUDh_NLs4RQJ8Ey780yY6k8OpWl4anR1BQ6tWGHc4P_dzvLUXbbvEqWUYG13l4NVK6Q6u9aPuJUQz1GIf8GDeCU-JOF3xInSrMc&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=be115cf3347efb4a']</value>
      <webElementGuid>1397c554-c29f-49d4-963a-b92eadff288d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
