<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14</name>
   <tag></tag>
   <elementGuidId>fd300542-821b-47fd-997d-8fe0800e7b60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c5b65945-6132-4b10-bac6-fe0f4aacba16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>6798afe2-27b9-4c0f-affe-81ad9ab06708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8</value>
      <webElementGuid>3e0da63e-6350-428b-8db3-d5cca0b70d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>ad94e0b1-be39-4758-9b6e-f7ffc1645d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-271pjynitv1e</value>
      <webElementGuid>5bb7cf85-7214-4ab5-831c-d7dd2c801936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>e11fffb8-68ef-4cf1-b8bb-1e5f085d860b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8')])[10]</value>
      <webElementGuid>0b3e7356-396d-45f4-9402-0ffaee545a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>4d20f79e-c799-4858-85db-0b04cebfa6a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KEOgqOp3tuL7hPfsEY2Wsq2DAczQa1PPe5qnvSaOHUVCB6vJcbrI4RgJk29BKmlu456a_1dKsciWJCzvD3fa2N-iV5SY4q6vMvHjonrqVjzupbyX2Pia_GL7yYH9J0WkcLOpPRS0kZ2AVSmrGd6SIPEAz3uqyWH2cv_nbSx09Ty5jXt4Pq7x8rpVhD7KAUFisB2_PrVfXSaWxBg5ir4SBOQYSkFEIUHR-E1ZKCxIbPeEY99M&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;id=e275bf41450171d8']</value>
      <webElementGuid>4e3cb66c-e530-47fa-85b9-7e6844cb17e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
