<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Dashboard_navbar-brand-img h-100</name>
   <tag></tag>
   <elementGuidId>0c6b5740-ac1f-4440-895f-0d0903e811b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='sidenav-main']/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.navbar-brand-img.h-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;main_logo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f1cb4656-2bdb-45a1-8074-70581f75cff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://folkatech.com/assets/images/logo-v2.png</value>
      <webElementGuid>beeae902-fcab-41af-a809-966295551376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-brand-img h-100</value>
      <webElementGuid>f302f933-399f-46a1-886e-bc17b1c0ad2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>main_logo</value>
      <webElementGuid>73ae736e-c2f3-43b0-9982-63244e2ceec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidenav-main&quot;)/div[@class=&quot;sidenav-header&quot;]/a[@class=&quot;navbar-brand m-0&quot;]/img[@class=&quot;navbar-brand-img h-100&quot;]</value>
      <webElementGuid>84128da2-804e-488e-ad95-228afbea3407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='sidenav-main']/div/a/img</value>
      <webElementGuid>075a44f6-c335-4275-b84e-e818a1bc5724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='main_logo']</value>
      <webElementGuid>839e2664-5162-406b-89fc-022b4af70022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>0fab0cf7-01ee-4f39-a794-206e831d9be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://folkatech.com/assets/images/logo-v2.png' and @alt = 'main_logo']</value>
      <webElementGuid>6979608f-a30b-4e39-88ac-ac1663997180</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
